### ISSUE TITLE
wrong object names in help files/objects

### ISSUE THREAD

**Issue by sebshader** [MikeMorenoAudio/pd-mkmr#1]
in pb.triangle~-help.pd it tries to create [pb.triangle] (no tilde)
in pb.saw~-help references [pb.saw], pb.square~-help references [pb.square]
in _filter-help rlpf~, rbpf1~, rbpf2~, and rhpf~ are referenced

(also hv.reverb tries to use hv.dispatch and hv.filter, which are not present and don't create)
thanks for the library, digging the instruments!

**Comment by MikeMorenoDSP** [comment]
Hello sebshader,
I should've done this a long time ago, thanks for the reminder.
All those references have been updated and hv.reverb is functional now.
Thanks! I'm glad you enjoy the instruments, let me know if you have any requests for one :)
